name: Response Time CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  response-time:
    runs-on: ubuntu-latest
    steps:
      - name: Run Upptime
        uses: upptime/uptime-monitor@v1.38.3
        with:
          command: "response-time"
