name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Upptime - readme
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Upptime - site
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Upptime - graphs
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Upptime - summary
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "summary"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
